name: Deploy Cloudflare Worker (Proxy)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - 'worker/**'

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Wrangler
        run: npm i -g wrangler
      - name: Configure secrets (GEMINI_API_KEY)
        run: echo "${{ secrets.GEMINI_API_KEY }}" | wrangler secret put GEMINI_API_KEY --quiet
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Configure secrets (ALLOWED_ORIGINS)
        run: echo "${{ secrets.ALLOWED_ORIGINS }}" | wrangler secret put ALLOWED_ORIGINS --quiet
        working-directory: worker
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Publish Worker
        run: wrangler deploy --account-id $CLOUDFLARE_ACCOUNT_ID
        working-directory: worker
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}


